### ISSUE TITLE
[macOS Ventura]: Coroutines not working

### ISSUE THREAD

**Issue by stalker-66** [coronalabs/corona#541] opened 2023-03-31 14:00 UTC
**Describe the bug**
On macOS Ventura, coroutines don't work in the simulator.

**To Reproduce**
Simulator crashes when launching coroutine:
```
local func = function()
	for i=1,100 do
		print( "i", i )
		coroutine.yield()
	end
end
local cor = coroutine.create(func)

local timerUpdate = timer.performWithDelay( 10, function(e)
	if coroutine.status(cor) ~= "dead" then
		coroutine.resume(cor)
	else
		timer.cancel(e.source)
	end
end, 0 )
```

The simulator crashes when using `display.captureScreen`. I think it also has to do with coroutines.

**Target platform and where build was made:**
macOS Ventura

**Additional context**
Simulator crashes with logs:
```
[Finished in 221.4s with exit code -11]
[cmd: '/Applications/Corona-3686/Corona Simulator.app/Contents/MacOS/Corona Simulator' -singleton 1 -no-console 1 /Users/narkoz/Repositories/BT/Client/main.lua]
[dir: /Users/narkoz/Repositories/BT/Client]
[path: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands]
```

**Comment by stalker-66** [comment] 2023-03-31 17:51
> I tried copying pasting you sample code into a project and don't get a crash on my m1 Mac <img alt="Screenshot 2023-03-31 at 10 23 17 AM" width="1085" src="https://user-images.githubusercontent.com/7820808/229147275-deac4e42-c230-482b-af7a-555c5ce30ee9.png">

Try to run several times.

**Comment by scottrules44** [comment] 2023-03-31 18:02
> Try to run several times.

I just tried 20 times, I am testing against 2023.3686, what version are you testing against?

**Comment by stalker-66** [comment] 2023-03-31 18:09
> > Try to run several times.
> 
> I just tried 20 times, I am testing against 2023.3686, what version are you testing against?

I have the same version 2023.3686. I will do more tests on other devices.

**Comment by stalker-66** [comment] 2023-03-31 18:14
> > Try to run several times.
> 
> I just tried 20 times, I am testing against 2023.3686, what version are you testing against?

Are you testing on macOS Ventura?

**Comment by scottrules44** [comment] 2023-03-31 18:21
> > > Try to run several times.
> > 
> > 
> > I just tried 20 times, I am testing against 2023.3686, what version are you testing against?
> 
> Are you testing on macOS Ventura?

Yes, Ventura 13.2.1

**Comment by elpida-v** [comment] 2023-04-07 17:58
@scottrules44 display.capture crashes on Corona version 3683 and onwards. To illustrate the problem I’ve created a simple project that only contains this code on main.lua: 

```
local staticImageBack = display.newRect(400,400,400,400)
staticImageBack:setFillColor(1,0,0)
display.capture(staticImageBack, {captureOffscreenArea=true, saveToPhotoLibrary=false})
```

The code runs without problems on version 3676 but crashes 90% of the times on version 3683. Check the uploaded video. I have also attached the code I run.

Please help. We are unable to submit our app, because we can't roll back to 3676 (due to Xcode incompatibility).

https://user-images.githubusercontent.com/59620078/230654695-20cb5931-622e-46ac-9e29-09b6f8e9b90d.mov

[Display Capture Crash on v3683.zip](https://github.com/coronalabs/corona/files/11180572/Display.Capture.Crash.on.v3683.zip)

**Comment by elpida-v** [comment] 2023-04-07 22:11
It seems that the crash only happens on the simulator. It runs fine on the iPhone. @scottrules44 @Shchvova @stalker-66 can you reproduce the simulator crash with the source code I shared above (on a Mac Ventura)?

**Comment by scottrules44** [comment] 2023-04-23 05:58
I will close this issue; I still cannot reproduce the issue with Coroutines; I assume the issue is with display.capture, which I just submitted a patch for.

If you still have experience issues and can attach a reproducible sample will happily reopen this issue :)

**Closed by scottrules44** 2023-04-23 05:58 UTC
