### ISSUE TITLE
print(os.date("%s")) crashes the sim

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#301] opened 2021-11-15 13:58 UTC
Place `print(os.date("%s")) crashes the sim` in main.lua and it crashes.  It should raise an error at the very least,

**Comment by XeduR** [comment] 2021-11-15 14:25
This quite a strange crash indeed.

It also doesn't seem to crash a built project. For instance, you can run the same code over at https://www.solar2dplayground.com/ and it'll just print "%s".

**Comment by scottrules44** [comment] 2021-11-16 03:04
Is this only happening on Windows? I just tried on my Mac, cannot reproduce

**Comment by XeduR** [comment] 2021-11-16 08:17
Yeah, we're both using Solar2D Simulator on Windows.

**Comment by scottrules44** [comment] 2022-12-24 18:12
This is fixed with 2022.3685+

**Closed by scottrules44** 2022-12-24 18:12 UTC
Labels: Windows
